import { standings, selectMatches, selectTournaments, calendarCells } from './model.js';
const root = document.querySelector('#app');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Intl.DateTimeFormat('en-US', {month:'short',day:'numeric',year:'numeric',timeZone:'America/Chicago'}).format(new Date(value.length === 10 ? `${value}T12:00:00-05:00` : value));
const time = value => new Intl.DateTimeFormat('en-US', {hour:'numeric',minute:'2-digit',timeZone:'America/Chicago',timeZoneName:'short'}).format(new Date(value));
const badge = '<span class="badge">SAMPLE</span>';
const state = {team:'all',competition:'all',year:2026,month:8};
let data;
const name = id => data.teams.find(t => t.id === id)?.name ?? 'Unknown team';
const empty = message => `<p class="empty">${message}</p>`;
function render() {
  const matches = selectMatches(data,state.team,state.competition);
  const tournaments = selectTournaments(data,state.team,state.competition);
  const isLeague = state.competition === 'all' || state.competition === data.competition_id;
  const table = isLeague ? standings(data,data.competition_id) : [];
  const rows = table.filter(t => state.team === 'all' || t.id === state.team);
  const profiles = data.teams.filter(t => (state.team === 'all' || t.id === state.team) && isLeague);
  const finals = matches.filter(m => m.status === 'final');
  const scheduled = matches.filter(m => m.status === 'scheduled');
  const monthName = new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(state.year,state.month,1)));
  root.innerHTML = `<section id="overview"><div class="section-heading"><div><p class="eyebrow">SEASON AT A GLANCE</p><h1>The Austin touchline</h1><p class="muted">${esc(data.season)} · ${esc(data.division)}</p></div><span class="snapshot">Results through ${date(data.rankings.as_of)}</span></div>
    <form class="filters" aria-label="Dashboard filters"><label>Team<select id="team-filter"><option value="all">All sample teams</option>${data.teams.map(t=>`<option value="${esc(t.id)}" ${state.team===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Competition<select id="competition-filter"><option value="all">All sample competitions</option><option value="${esc(data.competition_id)}" ${state.competition===data.competition_id?'selected':''}>SAMPLE League · U15 Demo Division</option>${data.tournaments.map(t=>`<option value="${esc(t.id)}" ${state.competition===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><button type="button" id="reset">Reset filters</button></form>
    <p class="filter-summary" role="status">Showing ${profiles.length} teams, ${matches.length} matches, and ${tournaments.length} tournaments. Standings retain their full competition position.</p>
    <div class="metrics"><article><span>Teams in view</span><strong>${profiles.length.toString().padStart(2,'0')}</strong><small>Austin-area sample clubs</small></article><article><span>Final results</span><strong>${finals.length.toString().padStart(2,'0')}</strong><small>Fictional completed matches</small></article><article><span>Scheduled matches</span><strong>${scheduled.length.toString().padStart(2,'0')}</strong><small>Illustrative fixtures</small></article><article><span>Tournaments</span><strong>${tournaments.length.toString().padStart(2,'0')}</strong><small>Unverified sample events</small></article></div></section>
    <div class="dashboard-grid"><section class="panel" id="standings"><div class="panel-heading"><div><p class="eyebrow">COMPETITION TABLE</p><h2>Standings</h2></div>${badge}</div><p class="muted">SAMPLE League · ${esc(data.division)}</p>${rows.length?`<div class="table-scroll" role="region" aria-label="Sample standings, scroll horizontally on small screens" tabindex="0"><table><caption class="sr-only">Sample league standings for ${esc(data.season)}</caption><thead><tr><th scope="col">Pos</th><th scope="col">Team</th>${['P','W','D','L','GF','GA','GD','Pts'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(t=>`<tr><td>${t.rank}</td><th scope="row">${esc(t.name)}</th>${[t.played,t.wins,t.draws,t.losses,t.goals_for,t.goals_against,t.goal_difference].map(v=>`<td>${v}</td>`).join('')}<td class="points">${t.points}</td></tr>`).join('')}</tbody></table></div>`:empty('No standings available for this competition. Tournament fixtures have not been recorded.')}<details><summary>How standings are calculated</summary><p>Final matches only. A win earns 3 points, a draw 1, and a loss 0. Ties are ordered by goal difference, then goals scored, then team name alphabetically. Selecting a team hides other rows without recalculating its position.</p><p>P = played; W/D/L = wins/draws/losses; GF/GA = goals for/against; GD = goal difference; Pts = points. Teams have played unequal numbers of matches.</p></details></section>
    <aside class="power-panel"><p class="eyebrow">SEPARATE FROM STANDINGS</p><h2>Power rankings</h2><span class="unavailable">Not available</span><p>Two fictional results are too little evidence to estimate team strength.</p><p>No power score or formula is applied. The standings show competition points only; they do not adjust for opponent strength or schedule difficulty.</p><div class="power-note">A future power model will need its own published formula, minimum match count, and uncertainty guidance.</div></aside></div>
    <section id="teams"><div class="section-heading"><div><p class="eyebrow">THE LOCAL FIELD</p><h2>Team profiles</h2></div>${badge}</div><div class="team-grid">${profiles.length?profiles.map(t=>{const stats=table.find(r=>r.id===t.id);return `<article class="team-card"><div class="team-top"><span class="team-monogram" aria-hidden="true">${esc(t.home_area.split(' ').map(w=>w[0]).join(''))}</span><span class="muted">${esc(t.age_group)} · SAMPLE</span></div><h3>${esc(t.name)}</h3><p class="muted">${esc(t.home_area)} · ${esc(data.division)}</p><div class="team-stats"><span><strong>${stats.played}</strong>Played</span><span><strong>${stats.points}</strong>Points</span><span><strong>${stats.goal_difference>0?'+':''}${stats.goal_difference}</strong>Goal diff.</span></div><div class="form-line"><span>Recent form</span><span aria-label="Results, oldest to newest">${stats.form.slice(-5).map(f=>`<abbr class="form-${f}" title="${{W:'Win',D:'Draw',L:'Loss'}[f]}">${f}</abbr>`).join('')||'No results'}</span></div><small>Oldest → newest · ${esc(data.season)}</small></article>`}).join(''):empty('No team profiles are linked to this competition. Tournament participants are unknown.')}</div></section>
    <section class="panel" id="matches"><div class="panel-heading"><div><p class="eyebrow">ON THE PITCH</p><h2>Match results & fixtures</h2></div>${badge}</div>${matches.length?matches.slice().sort((a,b)=>a.kickoff.localeCompare(b.kickoff)).map(m=>`<article class="match"><div class="match-date"><strong>${date(m.kickoff)}</strong><span>${time(m.kickoff)}</span></div><div class="match-score"><span>${esc(name(m.home_team_id))}<small>Home</small></span><strong>${m.status==='final'?`${m.home_score} <span>–</span> ${m.away_score}`:'vs'}</strong><span>${esc(name(m.away_team_id))}<small>Away</small></span></div><div class="match-meta"><span class="status ${m.status==='final'?'final':''}">${esc(m.status)}</span><small>${esc(m.venue)}</small><small>SAMPLE League · Fictional</small></div></article>`).join(''):empty('No matches match these filters. Tournament fixtures have not been recorded.')}</section>
    <section class="panel" id="calendar"><div class="panel-heading"><div><p class="eyebrow">PLAN AHEAD</p><h2>Tournament calendar</h2></div>${badge}</div><p class="muted">Sample dates only. Team participation is unknown; choosing a team hides events without confirmed team links.</p><div class="calendar-layout"><div><div class="month-controls"><button id="prev-month" aria-label="Previous month">←</button><h3>${monthName}</h3><button id="next-month" aria-label="Next month">→</button></div><div class="calendar-grid" role="group" aria-label="${monthName} sample tournaments">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<span class="weekday" >${d}</span>`).join('')}${calendarCells(state.year,state.month).map(day=>{const events=day?tournaments.filter(t=>day>=t.start_date&&day<=t.end_date):[];const deadlines=day?tournaments.filter(t=>day===t.registration_deadline):[];return `<div  class="calendar-day ${events.length?'event-day':''} ${deadlines.length?'deadline-day':''}" ${day?`aria-label="${date(day)}${events.length?', sample tournament':''}${deadlines.length?', sample registration deadline':''}"`:''}>${day?Number(day.slice(-2)):''}${events.length?'<span class="calendar-label">Cup</span>':''}${deadlines.length?'<span class="calendar-label">Due</span>':''}</div>`}).join('')}</div><p class="legend"><span>● Tournament</span><span>◌ Registration deadline</span></p></div><div class="event-list">${tournaments.filter(t=>t.start_date.slice(0,7)===`${state.year}-${String(state.month+1).padStart(2,'0')}`||t.end_date.slice(0,7)===`${state.year}-${String(state.month+1).padStart(2,'0')}`||t.registration_deadline.slice(0,7)===`${state.year}-${String(state.month+1).padStart(2,'0')}`).map(t=>`<article class="event-card"><span class="badge">ILLUSTRATIVE · SAMPLE</span><h3>${esc(t.name)}</h3><p>${date(t.start_date)} – ${date(t.end_date)}</p><p class="muted">${esc(t.venue)}<br>${esc(t.host_area)} · ${esc(t.age_group)}</p><dl><dt>Registration deadline</dt><dd>${date(t.registration_deadline)}</dd><dt>Participants & fixtures</dt><dd>Not yet recorded</dd><dt>Organizer / source</dt><dd>Unavailable — fictional event</dd></dl></article>`).join('')||empty('No sample tournaments or deadlines this month for these filters.')}</div></div></section>`;
  root.setAttribute('aria-busy','false');
  document.querySelector('#team-filter').addEventListener('change',e=>{state.team=e.target.value;render();document.querySelector('#team-filter').focus()});
  document.querySelector('#competition-filter').addEventListener('change',e=>{state.competition=e.target.value;render();document.querySelector('#competition-filter').focus()});
  document.querySelector('#reset').addEventListener('click',()=>{state.team='all';state.competition='all';render();document.querySelector('#reset').focus()});
  for (const [id,delta] of [['prev-month',-1],['next-month',1]]) document.querySelector(`#${id}`).addEventListener('click',()=>{const next=new Date(Date.UTC(state.year,state.month+delta,1));state.year=next.getUTCFullYear();state.month=next.getUTCMonth();render();document.querySelector(`#${id}`).focus()});
}
try {
  const response = await fetch('/data/sample/hub.json');
  if (!response.ok) throw new Error('Sample data could not be loaded');
  data = await response.json();
  if (data.data_status !== 'SAMPLE_ONLY' || !Array.isArray(data.teams) || !Array.isArray(data.matches) || !Array.isArray(data.tournaments)) throw new Error('Unsupported dataset');
  const start=data.tournaments[0]?.start_date ?? data.rankings.as_of;
  state.year=Number(start.slice(0,4));state.month=Number(start.slice(5,7))-1;
  document.querySelector('.season').textContent=data.season;
  render();
} catch(error) {
  root.setAttribute('aria-busy','false');
  root.innerHTML='<div role="alert" class="empty"><h1>Sample data unavailable</h1><p>Run the app with the local server and check data/sample/hub.json, then reload.</p><button onclick="location.reload()">Try again</button></div>';
  console.error(error);
}
